#!/usr/bin/env ruby

require "parseGVP"

begin
  option = ParseGVP::Option.new(ARGV)
  parser = ParseGVP::Parser.new(option.target)
  parser.call
  if option.has?(:verbose)
    print parser.detail_result
  elsif option.has?(:warning)
    print parser.warning_result
  else
    print parser.simple_result
  end
rescue
  print "ParseGVP Argument Error.\n"
end
