#!/usr/bin/env ruby

require "parseGVP"
require "optparse"

OPTS = {}

opt = OptionParser.new

opt.on('-v', "display detail result") { |v| OPTS[:v] = v }

opt.parse!(ARGV)

if ARGV.size == 1
  parser = ParseGVP::Parser.new(ARGV[0])
  parser.call
  if OPTS[:v]
    print parser.detail_result
  else
    print parser.simple_result
  end
else
  puts "ParseGVP Argument Error."
  puts
  print opt.help
end
